name: base_env_py3.9
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - dask
  - black
  - bottleneck
  - rope
  - ipykernel
  - geojson
  - bs4
  - hypothesis
  - pre-commit
  - requests
  - numexpr
  - scipy
  - pytest
  - pylint
  - python=3.9
  - netcdf4
  - matplotlib
  - xarray
  - lxml
  - python-dotenv
  - flask
  - flit