import os


# CROSS-MODULE VARIABLES
UUID = CREATION_TIME = None
LOG_CONFIG = dict()

# TESEO AUXILIARY DIRECTORIES
BIN_DIR = os.environ.get("TESEO_APIPROCESS_BIN_DIR")
DATA_DIR = os.environ.get("TESEO_APIPROCESS_DATA_DIR")
DOMAINS_DIR = os.path.join(DATA_DIR, "domains")
CONFIG_DIR = os.path.join(DATA_DIR, "config")

# JOBS PATHS & NAMES
JOBS_DIR = os.environ.get("TESEO_APIPROCESS_JOBS_DIR")
JOB_NAME = os.environ.get("TESEO_APIPROCESS_JOB_NAME")

# LOGS PATHS & NAMES
LOGS_DIR = os.environ.get("TESEO_APIPROCESS_LOGS_DIR")
LOG_FILENAME = os.environ.get("TESEO_APIPROCESS_LOG_FILENAME")

# DATABASES PATHS
OIL_DATABASE_PATH = os.environ.get("TESEO_APIPROCESS_OIL_DATABASE_PATH")
HNS_DATABASE_PATH = os.environ.get("TESEO_APIPROCESS_HNS_DATABASE_PATH")

# FLASK-API BASE URL
BASE_URL = os.environ.get("TESEO_APIPROCESS_BASE_URL")

# DATAHUCLIENT
DATAHUBCLIENT_AUTH = os.environ.get("DATAHUBCLIENT_AUTH")
